
name: CD

on:  
  pull_request:
    branches: [ master ]


jobs:
    
    test:
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - name: Olar
              run: echo "Olha o troxa" 
    