
name: CD

on:  
  pull_request:
    branches: [ master ]


jobs:
    test:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.labels[0].name == 'deploy'}}
        steps:
            - name: Olar
              run: |
                    echo "Olha o troxa" 
                    array = ${{ github.event.pull_request.labels }}
                    echo "${array[*]}"
                    event = ${{ github.event}}
                    echo "${event}"