
name: CD

on:  
  pull_request:
    branches: [ master ]


jobs:
    test:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push'}}
        steps:
            - name: Olar
              run: echo "Olha o troxa" 
    