# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
            ruby-version: '2.5.8' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - name: Deploying containers
        run: |
              docker-compose build
              docker-compose run web rails db:drop
              docker-compose run web rails db:create
              docker-compose run web rails db:migrate RAILS_ENV=test
              docker-compose run web rails db:test:prepare RAILS_ENV=test
              docker-compose run web rails db:seed RAILS_ENV=test

      - name: Run tests
        run: docker-compose run web bundle exec rspec --format doc
  rtc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gimmyxd/rtc-action@0.0.5
      env:
        FORCE_ERROR_EXIT: true
          UPDATE_PR: true

